{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintLambdaNat.
--   Generated by the BNF converter.

module PrintLambdaNat where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsLambdaNat

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsLambdaNat.Id where
  prt _ (AbsLambdaNat.Id i) = doc $ showString i

instance Print AbsLambdaNat.Program where
  prt i = \case
    AbsLambdaNat.Prog exps -> prPrec i 0 (concatD [prt 0 exps])

instance Print [AbsLambdaNat.Exp] where
  prt = prtList

instance Print AbsLambdaNat.Exp where
  prt i = \case
    AbsLambdaNat.EAbs id_ exp -> prPrec i 1 (concatD [doc (showString "\\"), prt 0 id_, doc (showString "."), prt 0 exp])
    AbsLambdaNat.EIf exp1 exp2 exp3 exp4 -> prPrec i 2 (concatD [doc (showString "if"), prt 0 exp1, doc (showString "="), prt 0 exp2, doc (showString "then"), prt 0 exp3, doc (showString "else"), prt 0 exp4])
    AbsLambdaNat.ELet id_ exp1 exp2 -> prPrec i 3 (concatD [doc (showString "let"), prt 0 id_, doc (showString "="), prt 0 exp1, doc (showString "in"), prt 0 exp2])
    AbsLambdaNat.ERec id_ exp1 exp2 -> prPrec i 4 (concatD [doc (showString "let"), doc (showString "rec"), prt 0 id_, doc (showString "="), prt 0 exp1, doc (showString "in"), prt 0 exp2])
    AbsLambdaNat.EHd exp -> prPrec i 6 (concatD [doc (showString "hd"), prt 0 exp])
    AbsLambdaNat.ETl exp -> prPrec i 6 (concatD [doc (showString "tl"), prt 0 exp])
    AbsLambdaNat.ELE exp1 exp2 -> prPrec i 9 (concatD [prt 10 exp1, doc (showString "less_equal"), prt 10 exp2])
    AbsLambdaNat.EPlus exp1 exp2 -> prPrec i 10 (concatD [prt 10 exp1, doc (showString "+"), prt 11 exp2])
    AbsLambdaNat.EMinus exp1 exp2 -> prPrec i 10 (concatD [prt 10 exp1, doc (showString "-"), prt 11 exp2])
    AbsLambdaNat.ETimes exp1 exp2 -> prPrec i 10 (concatD [prt 11 exp1, doc (showString "*"), prt 12 exp2])
    AbsLambdaNat.EApp exp1 exp2 -> prPrec i 13 (concatD [prt 13 exp1, prt 14 exp2])
    AbsLambdaNat.ENil -> prPrec i 15 (concatD [doc (showString "#")])
    AbsLambdaNat.ECons exp1 exp2 -> prPrec i 15 (concatD [prt 16 exp1, doc (showString ":"), prt 15 exp2])
    AbsLambdaNat.EInt n -> prPrec i 16 (concatD [prt 0 n])
    AbsLambdaNat.EVar id_ -> prPrec i 17 (concatD [prt 0 id_])
    AbsLambdaNat.EFix exp -> prPrec i 5 (concatD [doc (showString "fix"), prt 0 exp])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";;"), prt 0 xs]

